"""add last_known_ip to Device

Revision ID: 71a30ce6052b
Revises: 9ea4472f5194
Create Date: 2020-07-01 16:39:37.754264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71a30ce6052b'
down_revision = '9ea4472f5194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('last_known_ip', sa.String(length=46), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'last_known_ip')
    # ### end Alembic commands ###
