"""empty message

Revision ID: d1b4b2b9bd5a
Revises: 71a30ce6052b
Create Date: 2020-08-08 19:52:51.501389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1b4b2b9bd5a'
down_revision = '71a30ce6052b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_device_name', table_name='device')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_device_name', 'device', ['name'], unique=1)
    # ### end Alembic commands ###
